### ISSUE TITLE
Error while running npm start

### ISSUE THREAD

**Issue by vpramoth** [IBM/Decentralized-Energy-Composer#14]
![1](https://user-images.githubusercontent.com/8606203/32726691-d77bbe38-c89f-11e7-85df-0debc6bd93f9.png)

**Comment by raheelzubairy** [comment]
@vpramoth please try the updated instructions

**Comment by akumthek** [comment]
/var/hyperledger directory not getting created. 
$dist> composer runtime install    worked fine
but
$dist> composer network start
failed giving directory not found.

**Comment by raheelzubairy** [comment]
Please try the updated instructions with the latest Composer version. thanks
