### ISSUE TITLE
Gettting REST call error when deployed to a Ubuntu server

### ISSUE THREAD

**Issue by weipinhe** [IBM/Decentralized-Energy-Composer#15]
When I set up the app in a Ubuntu 16.04 LTS server and run it, I got this error when doing "Add Resident". 
Could not connect to REST server. Please check your configuration details

From Chrom I see the Coin API call is still pointing to port 3000 on localhost.
http://localhost:3000/api/Coins

Is there way to configure the Angular app to use the domain name and port of my own choosing to do the API calls?

Thanks!

**Comment by Hefziben** [comment]
Hello, where you able to find the solution? I am having the same issue. @weipinhe

**Comment by varunagarwal315** [comment]
@Hefziben Can you post details on exactly what the error is? Is there any error shown on any of the bash terminals?

**Comment by raheelzubairy** [comment]
Please try the instructions now for the latest version of Composer.  The configuration.ts contains the composer rest server information being called.  If you have the composer-rest-server deployed seperately with an IP address, you can update this file with the address. Thanks
