### ISSUE TITLE
Question : How did you generate "angular-app" folder?

### ISSUE THREAD

**Issue by rajadilipkolli** [IBM/Decentralized-Energy-Composer#19]
Hi ,

I just wanted to know the command you have used to generate the "angular-app" folder when I try to generate It is creating only for asset but not for participant, but in your example I can see it is generating for both of them.

**Comment by raheelzubairy** [comment]
@rajadilipkolli I created the participant and transactions separately by using similar format but making their respective rest-server api calls

**Comment by ganbadrakh** [comment]
@raheelzubairy would you show me your code/ commands, how you created participants and transactions?

**Comment by raheelzubairy** [comment]
I created participants and transactions with similar template as assets.  With the new update, the generator now is creating an angular app with participants and transactions: https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial
