### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by cenyuzhang** [IBM/Decentralized-Energy-Composer#2]
During step 3, npm install couldn't complete successfully. I am using node 8.4.0, npm 5.4.0 on Mac Sierra 10.12.6

<img width="954" alt="npm" src="https://user-images.githubusercontent.com/17069714/29799405-feb4ca52-8c28-11e7-9cbb-e32f9c682162.png">

**Comment by raheelzubairy** [comment]
Please try node 6.x
https://hyperledger.github.io/composer/installing/development-tools.html

**Comment by cenyuzhang** [comment]
@raheelzubairy thanks. Now the issue is to start the fabric. I had the following error when running the start fabric script.

<img width="953" alt="screen after starting fabric" src="https://user-images.githubusercontent.com/17069714/29852228-9b65350a-8cfe-11e7-8504-072d2ee1169b.png">

**Comment by raheelzubairy** [comment]
@cenyuzhang  I was unable to recreate the error.  Can you try removing docker processes and any existing relevant docker images and try again:
`docker kill $(docker ps -q)`
`docker rm $(docker ps -aq)`
`docker rmi $(docker images dev-* -q)`

**Comment by cenyuzhang** [comment]
There were several issues that I resolved, one issue was that the hyperledger fabric containers are v1.0.1, while the script was referring to v1.0.0. The other issue when trying to deploy the .bna file was due to the connection.json file under ~/.composer-connection-profiles. It uses localhost, while I have to change that to the docker-machine ip address. I will close out this issue.
