### ISSUE TITLE
--defaultchain flag should be removed

### ISSUE THREAD

**Issue by bh4rtp** [IBM/Decentralized-Energy-Composer#21]
--defaultchain flag was removed from the latest fabric. so the docker-composer.yml file should be revised in the configuration of peer0.org1.example.com. the start command can changed from
`command: peer node start --peer-defaultchain=false`
to be
`command: peer node start`

**Comment by raheelzubairy** [comment]
Updated fabric-tools for latest fabric v1.1.  Thanks
