### ISSUE TITLE
When I tried to web app hocalhost:4200. Could not connect in REST server.

### ISSUE THREAD

**Issue by yutapatio** [IBM/Decentralized-Energy-Composer#26]
I have done the steps to run the web app localhost:4200.
But, I got an error "Error; Could not connected to REST server. Please check your configuration details.

Could someone help me to solve this error?

Ubuntu16.4 and the environment is the same with samples.

**Comment by raheelzubairy** [comment]
@yutapatio could you share the error message in the terminal?

**Comment by yutapatio** [comment]
Hi, I got an another error, that is;
Starting business network decentralized-energy-network at version 0.1.15

Processing these Network Admins: 
	userName: admin

✖ Starting business network definition. This may take a minute...
Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message:  is not a valid endorsement system chaincode)
Command failed

**Comment by rghorpade** [comment]
I also got same error. After using composer v0.19.14 everything worked

**Comment by yutapatio** [comment]
Thank all. But I occurred another issue.
