### ISSUE TITLE
Utility Companies Link not working....

### ISSUE THREAD

**Issue by rghorpade** [IBM/Decentralized-Energy-Composer#28]
Everything working fine but "Utility Company" link is not working. 

When I put cursor on this link it shows "http://localhost:4200/Utility" and should be "http://localhost:4200/UtilityCompany" because all files are in that folder.

I tried my best but couldn't find solution.

How and where to change this? I am not an expert so asking this question.
Can anyone please help.

**Comment by raheelzubairy** [comment]
@rghorpade have made the fix.  You can always provide fixes through PRs. Thank you

commit: https://github.com/IBM/Decentralized-Energy-Composer/commit/47f6f9dbafd04006136b1aba6d5106eafab3c536
