### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by LennartFr** [IBM/Decentralized-Energy-Composer#3]
I am able to go thru the first two steps in the installation instructions on my MacBook.

In step three I then do:
Step 1: cd ../     // which brings me to the Decentralized-Energy-Composer directory
Step 2: npm install  //which works fine
Step 3: composer archive create -a dist/decentralized-energy-network.bna --sourceType dir --sourceName .

But there is no "composer" command in the Decentralized-Energy-Composer directory. On the other hand I can find a number of composer directories in the node-modules directory. 

Any idea what might be the trouble?

**Comment by ljbennett62** [comment]
@raheelzubairy - note @LennartFr issue with your app

**Comment by raheelzubairy** [comment]
@LennartFr - the composer cli package allows to run command line operations
Please use node version v6.x, and try installing composer cli and other Composer development tool:
`npm install -g composer-cli`
`npm install -g composer-rest-server`
`npm install -g generator-hyperledger-composer`

**Comment by LennartFr** [comment]
@raheelzubairy 

Thanks, Now I got all the way thru and have the app running! I intend to demo it at the Open Source Summit in Los Angeles next week.

Since running with a back level version of Node is key, it would be great if you could include something like " to install Node v6.* you can use nvm, see this URL: .https://davidwalsh.name/nvm

Something like that. Because if the reader is not a Node expert, installing an older Node version is not easy. Everything else works fine once has the right Node version.

I will send you some thoughts on how we can use this great app tomorrow.
