### ISSUE TITLE
bna file is having error. Not able to instantiate chaincode

### ISSUE THREAD

**Issue by tamaldas24** [IBM/Decentralized-Energy-Composer#31]
After generating the bna file not able to install it to fabric as it contains error.
Warning prepublish-on-install:
As of npm@5, prepublish scripts are deprecated.
Use prepare for build steps
Skipping optional dependency fsevents@1.2.4

found 94 vulnerabilities

During start of business network, chaincode error (status 500, message: is not a valid endorsement system chaincode)

**Comment by raheelzubairy** [comment]
@tamaldas24 are you still getting this error? Could you point which command is giving this error? the first message seems to be a warning
