### ISSUE TITLE
Migration to fabric-shim

### ISSUE THREAD

**Issue by varunagarwal315** [IBM/Decentralized-Energy-Composer#37]
As `composer` will no longer be getting updates from Fabric version 1.3, several people and projects, I imagine, would be looking to shift to either using `go` or `nodejs` for the `chaincode`.

I myself am migrating to `nodejs` and would like to create a public repository to demonstrate this exact same code base using nodejs but will require some additional collaborators to help out. Looking for some guidance.

Not sure where to post this so I opened an issue over here, hope that is ok with you. I am keen to learn and thought this is a good way to give back as well.

**Comment by ljbennett62** [comment]
@varunagarwal315 - it is our plan to migrate this to Fabric and away from Composer.  We will have another pattern for this.  We should have this in Q1.

**Comment by varunagarwal315** [comment]
@ljbennett62 OK sounds great, but as I am in the process of learning myself, I would love to have a chance to contribute to the new repo/ migration as I am going to start migrating my pilot on supply chain using composer, away from composer as well.

Please let me know how I can contribute to the new pattern.

**Comment by varunagarwal315** [comment]
Those looking at this, the new repo should be https://github.com/ljbennett62/decentralized-energy-fabric
@ljbennett62 Please confirm, then I can close this issue.
Out of curiosity, any reason why people are using `fabric-contract-api` over `fabric-shim` (apart from less boilerplate). I have only used the shim APIs

**Comment by ljbennett62** [comment]
@varunagarwal315 - so that is a temporary location - I will be moving this to the IBM org. I will be moving this week.  We are using `fabric-contract-api` based on guidance from the Blockchain documentation for using this with VS Code Blockchain extension.

**Comment by ljbennett62** [comment]
@varunagarwal315 - I have transferred the updating decentralized energy to the IBM org: https://github.com/IBM/decentralized-energy-fabric-on-IBP20

**Comment by varunagarwal315** [comment]
Great, I close this issue then?

**Comment by ljbennett62** [comment]
@varunagarwal315 - yes please - tx
