### ISSUE TITLE
Permissions feature

### ISSUE THREAD

**Issue by varunagarwal315** [IBM/Decentralized-Energy-Composer#8]
These lines in `permissions.acl` ensure any company can read any other company's data which is not ideal. I wanted to fork this repo and make it such that the read access to other utility companies data is revoked, so competing utility companies cannot read each other's data.

It is my understanding I will need to use `composer-passport` to achieve this, as I will be required to juggle multiple certificates for different users. Can I have some guidance for it please sir? I would want to work on this and contribute back to the project.

```
//Utility Companies to have access to their own account
rule UtilityCompanyAccessOwnRecord {
    description: "Allow utilty company to access only their profile"
    participant(p): "org.decentralized.energy.network.UtilityCompany"
    operation: READ, UPDATE, DELETE
    resource(r): "org.decentralized.energy.network.UtilityCompany"
    condition: (r.getIdentifier() === p.getIdentifier())
    action: ALLOW
}

//Utility Companies to have read only access to other Utility Companies
rule UtilityCompanyReadAccessUtilityCompanies {
    description: "Allow utility companies read access to other Utility Companies"
    participant: "org.decentralized.energy.network.UtilityCompany"
    operation: READ
    resource: "org.decentralized.energy.network.UtilityCompany"
    action: ALLOW
}
```

**Comment by raheelzubairy** [comment]
@varunagarwal315 sounds good.  The `permissions.acl` would be where you define the access.  You can look at `queries.qry` where some basic queries are defined, and used in `test.js` for each participant identity.
For authentication through rest server, I found this https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html

**Comment by varunagarwal315** [comment]
Yes, I am currently trying to run that link on a local deployment.  The `Roadmap` talks about specific permissions. What kind of permissions are you thinking of? I actually needed some guidance on how to go about coding it and then adding it to this repo as a PR.

BTW are you from the IBM team?

**Comment by raheelzubairy** [comment]
@varunagarwal315 We would like to access rest-server through each identity. I am part of the IBM team and would be interested to see specific permissions applied for each participant through the UI.

**Comment by varunagarwal315** [comment]
@raheelzubairy OK thanks, I will try to fork and do this. Any tips on how you would want me to proceed?

**Comment by varunagarwal315** [comment]
@raheelzubairy 

```
const resident_to_resident = factory.newTransaction(NS, 'EnergyToCoins');
resident_to_resident.energyRate = 4;
resident_to_resident.energyValue = 10;
resident_to_resident.coinsInc = factory.newRelationship(NS, 'Coins', 'CO_R1');
resident_to_resident.coinsDec = factory.newRelationship(NS, 'Coins', 'CO_R2');
resident_to_resident.energyInc = factory.newRelationship(NS, 'Energy', 'EN_R2');
resident_to_resident.energyDec = factory.newRelationship(NS, 'Energy', 'EN_R1');
```
These lines (703 - 709) call the `EnergyToCoins` function that updates values for R1 and R2. However the identity used is R2, so the transaction cannot be completed. 

I am a bit confused on how to solve this problem. Even if I were to split the transaction into two parts where R1 were to `propose` the transaction and R2 were to `accept` it, a similar problem would be faced.

I have opened [a question](https://stackoverflow.com/questions/47305764/permissioning-in-hyperlededger-fabric-composer-transactions) on stackoverflow, but got one incorrent answer so far.

**Comment by raheelzubairy** [comment]
Sorry for not being responsive. The permissions acl file would need to be updated.
